version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - 2181:2181
    networks:
      - demo-network      
      
  kafka:
    image: wurstmeister/kafka
    ports:
      - 9092:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092    
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - demo-network      

  demo-producer:
    image: ntlong1594/kafka-demo-producer
    ports:
      - 1000:1000
    restart: always
    depends_on:
      - kafka
    networks:
      - demo-network
      
  demo-truck-consumer:
    image: ntlong1594/kafka-demo-producer
    ports:
      - 2000:2000
    restart: always
    depends_on:
      - kafka
    networks:
      - demo-network
      
  demo-plane-consumer:
    image: ntlong1594/kafka-demo-producer
    ports:
      - 3000:3000
    restart: always
    depends_on:
      - kafka
    networks:
      - demo-network
      
networks:
  demo-network:
    driver: bridge