version: '2'
services:
  point:
    image: ntlong1594/kafka-demo-point-consumer
    environment:
      - SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS=kafka
    ports:
      - 4000:4000
    restart: always