version: '2'
services:
  viettelpost:
    image: ntlong1594/kafka-demo-viettelpost-consumer
    environment:
      - SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS=kafka
    ports:
      - 2000:2000
    restart: always