server.port: 1000
logging.level.root: WARN
spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost
          defaultBrokerPort: 9092
          minPartitionCount: 2
          autoCreateTopics: true
          autoAddPartitions: true
      bindings:
        orderStorageImportChannel:
          destination: orderStorageTopic
          contentType: application/json