server.port: 2000
spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost
          defaultBrokerPort: 9092
          minPartitionCount: 3
          autoCreateTopics: true
          autoAddPartitions: true
      bindings:
        orderStorageDeliveryChannel:
          destination: orderStorageTopic
          contentType: application/json
          group: orderStorageConsumer

